# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\TinyWindows\Documents\PSoC Creator\My First Project\My First Project.cydsn\My First Project.cyprj
# Date: Wed, 08 Jul 2015 22:22:55 GMT
#set_units -time ns
create_clock -name {Clock_1(FFB)} -period 500 -waveform {0 250} [list [get_pins {ClockBlock/ff_div_8}]]
create_clock -name {CyHFCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/hfclk}] -edges {1 13 25} [list]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CySYSCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]


# Component constraints for C:\Users\TinyWindows\Documents\PSoC Creator\My First Project\My First Project.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\TinyWindows\Documents\PSoC Creator\My First Project\My First Project.cydsn\My First Project.cyprj
# Date: Wed, 08 Jul 2015 22:22:50 GMT
